//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW3Tests.StockDataPointsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDataPoints", Namespace="http://schemas.datacontract.org/2004/07/StockDataPointsService")]
    [System.SerializableAttribute()]
    public partial class StockDataPoints : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockDataPointsService.IStockDataPointsService")]
    public interface IStockDataPointsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockDataPointsService/GetStockDataPoints", ReplyAction="http://tempuri.org/IStockDataPointsService/GetStockDataPointsResponse")]
        HW3Tests.StockDataPointsService.StockDataPoints GetStockDataPoints(string stockTicker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockDataPointsService/GetStockDataPoints", ReplyAction="http://tempuri.org/IStockDataPointsService/GetStockDataPointsResponse")]
        System.Threading.Tasks.Task<HW3Tests.StockDataPointsService.StockDataPoints> GetStockDataPointsAsync(string stockTicker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockDataPointsServiceChannel : HW3Tests.StockDataPointsService.IStockDataPointsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockDataPointsServiceClient : System.ServiceModel.ClientBase<HW3Tests.StockDataPointsService.IStockDataPointsService>, HW3Tests.StockDataPointsService.IStockDataPointsService {
        
        public StockDataPointsServiceClient() {
        }
        
        public StockDataPointsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockDataPointsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockDataPointsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockDataPointsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HW3Tests.StockDataPointsService.StockDataPoints GetStockDataPoints(string stockTicker) {
            return base.Channel.GetStockDataPoints(stockTicker);
        }
        
        public System.Threading.Tasks.Task<HW3Tests.StockDataPointsService.StockDataPoints> GetStockDataPointsAsync(string stockTicker) {
            return base.Channel.GetStockDataPointsAsync(stockTicker);
        }
    }
}
