//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsoleApp.StorageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService.IStorageService")]
    public interface IStorageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/uploadFile", ReplyAction="http://tempuri.org/IStorageService/uploadFileResponse")]
        string uploadFile(System.IO.Stream uploadedFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/uploadFile", ReplyAction="http://tempuri.org/IStorageService/uploadFileResponse")]
        System.Threading.Tasks.Task<string> uploadFileAsync(System.IO.Stream uploadedFile);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorageServiceChannel : TestConsoleApp.StorageService.IStorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<TestConsoleApp.StorageService.IStorageService>, TestConsoleApp.StorageService.IStorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string uploadFile(System.IO.Stream uploadedFile) {
            return base.Channel.uploadFile(uploadedFile);
        }
        
        public System.Threading.Tasks.Task<string> uploadFileAsync(System.IO.Stream uploadedFile) {
            return base.Channel.uploadFileAsync(uploadedFile);
        }
    }
}
