//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW3Tests.StorageService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StorageService1.IStorageService")]
    public interface IStorageService {
        
        // CODEGEN: Generating message contract since the wrapper name (FileUpload) of message FileUpload does not match the default value (uploadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/uploadFile", ReplyAction="http://tempuri.org/IStorageService/uploadFileResponse")]
        HW3Tests.StorageService1.FileUploadResponse uploadFile(HW3Tests.StorageService1.FileUpload request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStorageService/uploadFile", ReplyAction="http://tempuri.org/IStorageService/uploadFileResponse")]
        System.Threading.Tasks.Task<HW3Tests.StorageService1.FileUploadResponse> uploadFileAsync(HW3Tests.StorageService1.FileUpload request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUpload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUpload {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string nameOfFile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream uploadedFileDataStream;
        
        public FileUpload() {
        }
        
        public FileUpload(string nameOfFile, System.IO.Stream uploadedFileDataStream) {
            this.nameOfFile = nameOfFile;
            this.uploadedFileDataStream = uploadedFileDataStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileURL;
        
        public FileUploadResponse() {
        }
        
        public FileUploadResponse(string FileURL) {
            this.FileURL = FileURL;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStorageServiceChannel : HW3Tests.StorageService1.IStorageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StorageServiceClient : System.ServiceModel.ClientBase<HW3Tests.StorageService1.IStorageService>, HW3Tests.StorageService1.IStorageService {
        
        public StorageServiceClient() {
        }
        
        public StorageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StorageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HW3Tests.StorageService1.FileUploadResponse HW3Tests.StorageService1.IStorageService.uploadFile(HW3Tests.StorageService1.FileUpload request) {
            return base.Channel.uploadFile(request);
        }
        
        public string uploadFile(string nameOfFile, System.IO.Stream uploadedFileDataStream) {
            HW3Tests.StorageService1.FileUpload inValue = new HW3Tests.StorageService1.FileUpload();
            inValue.nameOfFile = nameOfFile;
            inValue.uploadedFileDataStream = uploadedFileDataStream;
            HW3Tests.StorageService1.FileUploadResponse retVal = ((HW3Tests.StorageService1.IStorageService)(this)).uploadFile(inValue);
            return retVal.FileURL;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HW3Tests.StorageService1.FileUploadResponse> HW3Tests.StorageService1.IStorageService.uploadFileAsync(HW3Tests.StorageService1.FileUpload request) {
            return base.Channel.uploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<HW3Tests.StorageService1.FileUploadResponse> uploadFileAsync(string nameOfFile, System.IO.Stream uploadedFileDataStream) {
            HW3Tests.StorageService1.FileUpload inValue = new HW3Tests.StorageService1.FileUpload();
            inValue.nameOfFile = nameOfFile;
            inValue.uploadedFileDataStream = uploadedFileDataStream;
            return ((HW3Tests.StorageService1.IStorageService)(this)).uploadFileAsync(inValue);
        }
    }
}
