//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockChartService.StockDataPoints {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDataPoints", Namespace="http://schemas.datacontract.org/2004/07/StockDataPointsService")]
    [System.SerializableAttribute()]
    public partial class StockDataPoints : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StockChartService.StockDataPoints.StockDataPoint[] DataPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double currentPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lastMonthPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double lastYearPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stockTickerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StockChartService.StockDataPoints.StockDataPoint[] DataPoints {
            get {
                return this.DataPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataPointsField, value) != true)) {
                    this.DataPointsField = value;
                    this.RaisePropertyChanged("DataPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double currentPrice {
            get {
                return this.currentPriceField;
            }
            set {
                if ((this.currentPriceField.Equals(value) != true)) {
                    this.currentPriceField = value;
                    this.RaisePropertyChanged("currentPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lastMonthPrice {
            get {
                return this.lastMonthPriceField;
            }
            set {
                if ((this.lastMonthPriceField.Equals(value) != true)) {
                    this.lastMonthPriceField = value;
                    this.RaisePropertyChanged("lastMonthPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double lastYearPrice {
            get {
                return this.lastYearPriceField;
            }
            set {
                if ((this.lastYearPriceField.Equals(value) != true)) {
                    this.lastYearPriceField = value;
                    this.RaisePropertyChanged("lastYearPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string stockTicker {
            get {
                return this.stockTickerField;
            }
            set {
                if ((object.ReferenceEquals(this.stockTickerField, value) != true)) {
                    this.stockTickerField = value;
                    this.RaisePropertyChanged("stockTicker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDataPoint", Namespace="http://schemas.datacontract.org/2004/07/StockDataPointsService")]
    [System.SerializableAttribute()]
    public partial class StockDataPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockDataPoints.IStockDataPointsService")]
    public interface IStockDataPointsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockDataPointsService/GetStockDataPoints", ReplyAction="http://tempuri.org/IStockDataPointsService/GetStockDataPointsResponse")]
        StockChartService.StockDataPoints.StockDataPoints GetStockDataPoints(string stockTicker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockDataPointsService/GetStockDataPoints", ReplyAction="http://tempuri.org/IStockDataPointsService/GetStockDataPointsResponse")]
        System.Threading.Tasks.Task<StockChartService.StockDataPoints.StockDataPoints> GetStockDataPointsAsync(string stockTicker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockDataPointsServiceChannel : StockChartService.StockDataPoints.IStockDataPointsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockDataPointsServiceClient : System.ServiceModel.ClientBase<StockChartService.StockDataPoints.IStockDataPointsService>, StockChartService.StockDataPoints.IStockDataPointsService {
        
        public StockDataPointsServiceClient() {
        }
        
        public StockDataPointsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockDataPointsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockDataPointsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockDataPointsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StockChartService.StockDataPoints.StockDataPoints GetStockDataPoints(string stockTicker) {
            return base.Channel.GetStockDataPoints(stockTicker);
        }
        
        public System.Threading.Tasks.Task<StockChartService.StockDataPoints.StockDataPoints> GetStockDataPointsAsync(string stockTicker) {
            return base.Channel.GetStockDataPointsAsync(stockTicker);
        }
    }
}
